<?php


namespace App\HttpController;

use EasySwoole\Http\AbstractInterface\Controller;


class Ctrl extends Controller
{
    function index()
    {
        echo "hello";
    }

    //打印数据 捕获再写入
    function afterAction(?string $actionName): void
    {
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
        $rt = ob_get_clean();
        $this->response()->write($rt);
        //设置中文
        $this->response()->withHeader('Content-type', 'application/json;charset=utf-8');
    }

    //输出数据先写入缓存
    function onRequest(?string $action): ?bool
    {
        ob_start();
        //echo "-_-ob_start\n";
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }
}